### ISSUE TITLE
404 javascript files

### ISSUE THREAD

**Issue by Gocht** [wildfish/swampdragon-django-notifications-demo#1]
This example have 404 errors in template's javascript references.

**Comment by hagsteel** [comment]
Ah yes, SwampDragon was updated recently. Will update this tutorial now

**Comment by Gocht** [comment]
Are all the needed javascript files in static folder now?

**Comment by hagsteel** [comment]
You have to do a pip install swampdragon --upgrade  (assuming you use pip).

**Comment by Gocht** [comment]
I'll try. Is there any difference using dragon-admin instead django-admin further settings aditional line?

**Comment by hagsteel** [comment]
There is not, no.
If you are putting this into an existing project you can simply add the two require settings.

**Comment by Gocht** [comment]
Have you tested this on mobile browsers?

**Comment by hagsteel** [comment]
I have not.

The tests I've done are the following:

Django 1.6.8 and 1.7.1, and python 2.7.4 and python 3.4, with the following browsers:
-  Chrome 39.0.2171.71 (64-bit)
-  Safari 8.0 (10600.1.25.1)
-  Firefox developer edition 36.0a2 (2014-12-07)

Mind you, that was not with the latest version of SD but the one before.

Looking at this however: http://caniuse.com/#feat=notifications
I would say desktop notifications doesn't work.

I have tested other SD related apps on mobiles and they work a treat (when I started writing SD it even worked on a Sony eInk reader, though I'm not sure that is the case anymore).

**Comment by Gocht** [comment]
I'm trying from a mobile browser (Chrome 40) but i have no reaction in real-time I have to reload the page to get the new item... Have you tried something like that? I think is something with the server running at :9999. I'm using just the django built-in server for testing.

**Comment by hagsteel** [comment]
Make sure your phone and your server are on the same network (this doesn't have to be the case once the application is deployed of course).

Let's say your local ip address is 192.168.1.100

Update your settings file:

`DRAGON_URL = 'http://192.168.1.100:9999/'`

Then to run:

Start Django dev server: `./manage.py runserver 0.0.0.0:8000`
Start SwampDragon server: `./manage.py runsd 0.0.0.0:9999`

You should now be able to access this from your phone by browsing http://192.168.1.100:8000

**Comment by Gocht** [comment]
That worked for me, Thakns! Have you try to remove the desktop notification and use just the real-time in page?

**Comment by hagsteel** [comment]
I am actually working on a notification module where I've made desktop notifications optional through user settings.

The package is only handling notifications for signed in users and it's not production ready but feel free to have a poke: https://github.com/jonashagstedt/swampdragon-notifications

**Comment by Gocht** [comment]
Nice, now I'm trying to use this demo with MongoDB, where I stored my notifications, and I'd like to remove the desktop notifications... I wonder if possible, you think?. Thanks for sharong me your work.

**Comment by hagsteel** [comment]
If you want to remove desktop notifications simply delete this function:

https://github.com/wildfish/swampdragon-django-notifications-demo/blob/master/static/notifications.js#L3

and this if statement: 
https://github.com/wildfish/swampdragon-django-notifications-demo/blob/master/static/notifications.js#L37

(if I understood you correctly)

**Comment by Gocht** [comment]
Yep!, that is. thanks! Now I keep trying to use mongoDB, I hope..

**Comment by Gocht** [comment]
Well, I think it's not supported, I got AttributeError...

**Comment by hagsteel** [comment]
I don't think the self publishing models are compatible with MongoDB.

I would recommend you remove the SelfPublishModel and Serializer from the models and write a function to explicitly publish notifications.

```
def publish_notification(notification):
    data = {
        'message': notification.message
    }
    publish_data(channel='notifications', data=notification)
```

You can then pass in your MongoDB object as a notification (assuming in this example that you have a property called `message` and you have subscribed to a channel called "notifications").

When you want to publish a notification you simply call `publish_notification`

**Comment by Gocht** [comment]
SD has no documentation for it I guess...

**Comment by Gocht** [comment]
I'd like to know where belongs that publish_data method

**Comment by hagsteel** [comment]
First setup your router. Instead of ModelRouter you use a BaseRouter.

```
class NotificationRouter(BaseRouter):
    route_name = 'notifications'

    def get_subscription_channels(self, **kwargs):
        return ['notifications']


route_handler.register(NotificationRouter)
```

I don't know what your notification model looks like so let's just say it's an object with a `message` property.

Add a function for publishing your notifications:

```
def publish_notification(notification):
    data = {
        'message': notification.message
    }
    publish_data(channel='notifications', data=notification)
```

Again, I'm unusure of MongoDB and models, but whenever you create a notification model you can also call `publish_notification`.

If the model have a save function you could override it:

```
def save(self, *args, **kwargs):
    if self.id is None:  # Only publish the notification if it's a new one
        publish_notification(self)
    super().save(*args, **kwargs)
```

Even better would be to call `publish_notification` from a manager.

Hope this helps

**Comment by Gocht** [comment]
I see that `publish_data` method and it looks magic, but where is it from? Just like in [docs](http://swampdragon.net/documentation/publishing-data/) not specify where import from

**Comment by hagsteel** [comment]
`from swampdragon.pubsub_providers.data_publisher import publish_data`
